[package]
name = "mdl"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"

[dependencies]
mdl-sys = {path="../mdl-sys"}
snafu = "0.4.1"
lazy_static = "1.3.0"
