[package]
name = "mdl"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"

[dependencies]
mdl-sys = {path="../mdl-sys"}
lazy_static = "1.3.0"
err-derive = "0.1.5"

[dev-dependencies]
cuda-sys = "0.2.0"
structopt = "0.2"
